#!/bin/bash

cfg=${XDG_CONFIG_HOME:-"$HOME"/.config}
level=$(xbacklight)

if (( "${level%%.*}" )); then
	xbacklight > "$cfg/scrn_tog_brightness"
	xbacklight -set 0
else
	xbacklight -set "$(< $cfg/scrn_tog_brightness)"
	printf %s "$level" > "$cfg/scrn_tog_brightness"
fi
