#!/bin/bash

primary="$(xrandr | grep ' connected ' | awk 'NR==1{print $1}')"
declare -A positions
count=0

while read -r line; do
    ((count++))
    if [[ "$line" == "$primary" ]]; then
        continue
    fi
    positions["$line"]="$(echo -e "right-of\nleft-of\nabove\nbelow\ndisable $line" | dmenu -p "On which side of $primary do you want to put $line?")"
done <<< "$(xrandr | grep " connected " | awk '{print $1}')"

final_str="xrandr --output $primary --auto"

for key in "${!positions[@]}"; do
    final_str=$final_str" --output $key"
    if ! [[ ${positions[$key]} == "disable $key" ]]; then
        final_str=$final_str" --auto --${positions[$key]} $primary"
    else
        final_str=$final_str" --off"
    fi
done

if (( count == 1 )); then
    xrandr --auto    
else
    $final_str
fi