#!/bin/sh
if xinput list-props 'SynPS/2 Synaptics TouchPad' | grep "Device Enabled" | grep -q 0; then
	xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1
	notify-send -a "Touchpad Toggle" "Touchpad enabled."
else
	xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
	notify-send -a "Touchpad Toggle" "Touchpad disabled."
fi
