#!/bin/bash

status="$(lsmod | grep uvcvideo)"

if [ -z "$status" ]; then
	pkexec sudo modprobe uvcvideo
	notify-send -a "Webcam Button" "Webcam enabled."
else
	pkexec sudo modprobe -r uvcvideo
	notify-send -a "Webcam Button" "Webcam disabled."
fi
